SET autocommit=0;
START TRANSACTION;
DROP TABLE info_utilitzacio;
DROP TABLE pasi_expres;
DROP TABLE tipus_acces_atraccio;
DROP TABLE entrada_parc;
DROP TABLE preu_parc;
SET foreign_key_checks = 0;
DROP TABLE atraccio;
DROP TABLE incidencia;
SET foreign_key_checks = 1;
DROP TABLE entrada;
DROP TABLE tipus_pasi_expres;
DROP TABLE zona;
DROP TABLE parc;
DROP TABLE client;
DROP TABLE preu;
DROP TABLE estat_operatiu;
DROP TABLE tipus_acces;
DROP TABLE categoria_entrada;
COMMIT;